### ISSUE TITLE
Middleware should be opt-in like express

### ISSUE THREAD

**Issue by DaleJefferson** [kogosoftwarellc/express-openapi#13]
This project has been really nicely designed to be modular with separated middleware, but all of the middleware seems to be included by default. In express, koa and other frameworks all middleware is optional so you are free to add what you wish and use alternatives which allows for a rich ecosystem.

I suggest we define a middleware spec for express-openapi.

```
function myCoolMiddleware(apiDoc) {
    return function (req, res, next) {
        // Do stuff
        next();
    }
}

// or

function myCoolMiddleware(req, res, next) {
   const apiDoc = req.apiDoc;   
   // Do stuff
   next();
}

const openapiInstance = openapi.initialize({
});

openapiInstance.use(myCoolMiddleware);

// or

openapi.initialize({
    middleware: [myCoolMiddleware, express-openapi-defaults]
});
```

**Comment by jsdevel** [comment]
`express-openapi` has the notion of `scoped` middleware.  Checkout https://github.com/kogosoftwarellc/express-openapi#supported-vendor-extensions.

You can accomplish what you want by doing this in your apiDoc:

```
'x-express-openapi-disable-middleware': true
'x-express-openapi-additional-middleware': [myCoolMiddleware, expressOpenapiDefaults]
```

The problem is that `express-openapi-defaults` directly depends on your operation doc, so it's almost necessary that it's baked in and managed with vendor extensions.

**Comment by jsdevel** [comment]
FYI, `koa-openapi` is now ready.
